class CustomException(Exception):
    pass

class NotFoundException(Exception):
    pass